sudo: required

services:
  - docker

before_install:
  - chmod +x ./upload.sh

script:
  - cd ./ANNA
  - docker run -it -v `pwd`:/mnt/src beevelop/latex dokumentation

after_script:
  - cd ..
  - ./upload.sh
